### ISSUE TITLE
Look for all variations of readme.

### ISSUE THREAD

**Issue by sharu725** [AndreVarandas/fetch-readme#60]
Just a suggestion. Can the package look for variations of readme if ``README.md`` is not found?
I have seen people having readme files like ``Readme.md``, ``readme.md`` etc.
Github seems to parse it correctly in the repo page.

**Comment by AndreVarandas** [comment]
Hi @sharu725 thanks for your interest in the package. Unfortunately, by the time I built it I decided to go for a configuration based approach, in which you can specify the file name. But now I would instead make it look for `README.md`, `Readme.md` and `readme.md`. 

Would you like to add this feature?
